export default function AiResultModal({
  open,
  title,
  loading,
  content,
  onClose,
  cached,
}) {
  if (!open) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40">
      <div className="bg-white w-full max-w-2xl max-h-[80vh] rounded-xl shadow-lg p-6 flex flex-col">
        {/* ===== Header ===== */}
        <div className="flex justify-between items-center mb-2">
          <h2 className="font-semibold text-lg">{title}</h2>
          <button onClick={onClose} className="text-gray-500 hover:text-black">
            ✕
          </button>
        </div>

        {/* ===== Cache indicator ===== */}
        {!loading && (
          <p className="text-xs mb-3 text-gray-500">
            {cached ? "⚡ Loaded from cache" : "🧠 Generated by AI"}
          </p>
        )}

        {/* ===== Content ===== */}
        {loading ? (
          <p className="text-sm text-gray-500">AI is thinking...</p>
        ) : (
          <div className="prose max-w-none whitespace-pre-line overflow-y-auto flex-1 pr-2">
            {content || "No content generated."}
          </div>
        )}
      </div>
    </div>
  );
}
